import { slugify } from "@/src/lib/slug";
import type { ServiceType } from "@/src/lib/routes";

const bangaloreAreaNames = [
  "BTM Layout",
  "Electronic City",
  "Koramangala",
  "HSR Layout",
  "Whitefield",
  "Mahadevapura",
  "Jayanagar",
  "Rajajinagar",
  "Malleshwaram",
  "Chickpet",
  "Marathahalli",
  "JP Nagar",
  "Banashankari",
  "Bommanahalli",
  "Channasandra",
  "Commercial Street",
  "Kundanahalli",
  "RT Nagar",
  "Basaveshwaranagar",
  "Domlur",
  "Brigade Road",
  "Yelahanka",
  "Kengeri",
  "Mathikere",
  "Yeshwantpur",
  "ITPL Bangalore",
  "Ramanagara",
  "Sarjapur Road",
  "Uttarahalli",
  "SP Road",
  "Richmond Town",
  "Murphy Town",
  "Fraser Town",
  "Cox Town",
  "Sadashivnagar",
  "Seshadripuram",
  "Shivajinagar",
  "Ulsoor",
  "Vasanth Nagar",
  "Hoodi",
  "Varthur",
  "Horamavu",
  "Kalyan Nagar",
  "Kammanahalli",
  "Lingarajapuram",
  "Ramamurthy Nagar",
  "Hebbal",
  "Jalahalli",
  "Peenya",
  "Vidyaranyapura",
  "Bommasandra",
  "Madivala",
  "Basavanagudi",
  "Indiranagar",
  "Giri Nagar",
  "Kumaraswamy Layout",
  "KR Market",
  "Padmanabhanagar",
  "Anjanapura",
  "Kempegowda",
  "Arekere",
  "Hoskote",
  "Begur",
  "Gottigere",
  "Hulimavu",
  "Kamakshipalya",
  "Mahalakshmi Layout",
  "Nagarbhavi",
  "Nandini Layout",
  "Attibele",
  "Jigani",
  "Anekal",
  "MG Road",
  "Majestic",
  "Chandapura",
  "Nelamangala",
  "HBR Layout",
  "Benson Town",
  "Rajarajeshwari Nagar",
  "Malleshpalya",
  "Koramangala 1st Block",
  "Koramangala 2nd Block",
  "Koramangala 3rd Block",
  "Koramangala 4th Block",
  "Koramangala 5th Block",
  "Koramangala 6th Block",
  "Koramangala 7th Block",
  "Koramangala 8th Block",
  "Koramangala 9th Block",
  "Cunningham Road",
  "Jeevan Bima Nagar",
  "Frazer Town",
  "Hennur",
  "Sahakar Nagar",
  "Sahakara Nagar",
  "Jayamahal",
  "Cooke Town",
  "HRBR Layout",
  "Sanjay Nagar",
  "Shanti Nagar",
  "Adugodi",
  "Langford Town",
  "Wilson Garden",
  "JP Nagar 1st Phase",
  "JP Nagar 2nd Phase",
  "JP Nagar 3rd Phase",
  "JP Nagar 4th Phase",
  "JP Nagar 5th Phase",
  "JP Nagar 6th Phase",
  "JP Nagar 7th Phase",
  "JP Nagar 8th Phase",
  "JP Nagar 9th Phase",
  "Electronic City Phase 1",
  "Electronic City Phase 2",
  "Doddanekundi",
  "Ramagondanahalli",
  "Gunjur",
  "Silk Board",
  "Bellandur",
  "Marathahalli Bridge",
  "Kadubeesanahalli",
  "Panathur",
  "Belathur",
  "Carmelaram",
  "Kadugodi",
  "Hagadur",
  "Munnekolal",
  "Varthur Road",
  "Kundalahalli",
  "Hope Farm",
  "Brookefield",
  "Nallurhalli",
  "Whitefield Main Road",
  "Nellurahalli",
  "Vinayakanagar",
  "Immadihalli",
  "Siddapura",
  "Thubarahalli",
  "Kempapura",
  "ECC Road",
  "Pattandur Agrahara",
  "Avalahalli",
  "Doddabommasandra",
  "Amruthahalli",
  "Ganganagar",
  "Hebbal Kempapura",
  "Byatarayanapura",
  "RMV Extension",
  "Sanjeevini Nagar",
  "Goraguntepalya",
  "Sultanpalya",
  "Jakkur",
  "Yeshwanthpur Industrial Area",
  "Kacharakanahalli",
  "Jayanti Nagar",
  "Hennur Road",
  "HBR Layout 1st Block",
  "HBR Layout 2nd Block",
  "HBR Layout 3rd Block",
  "HBR Layout 4th Block",
  "HBR Layout 5th Block",
  "Medahalli",
  "Munireddy Layout",
  "Jalahalli West",
  "MS Palya",
  "Chikkagubbi",
  "Kalyan Nagar 4th Block",
  "Horamavu Banjara Layout",
  "BEL Road",
  "Jakkuru Layout",
  "NRI Layout",
  "Thanisandra Main Road",
  "Byrathi Village",
  "Amrutahalli",
  "Chokkanahalli",
  "Hormavu Agara",
  "Narayanapura",
  "Sadashivanagar",
  "Yeswanthpur",
] as const;

export type BangaloreArea = {
  name: string;
  slug: string;
};

export const bangaloreAreas: BangaloreArea[] = bangaloreAreaNames.map((name) => ({
  name,
  slug: slugify(name),
}));

export function getBangaloreAreaBySlug(areaSlug: string) {
  return bangaloreAreas.find((area) => area.slug === areaSlug) ?? null;
}

export function buildBangaloreAreaRoute(areaSlug: string) {
  return `/bangalore/${areaSlug}`;
}

export function buildBangaloreAreaServiceRoute(areaSlug: string, serviceType: ServiceType) {
  return `/bangalore/${areaSlug}/service/${serviceType}`;
}
