/**
 * Image registry.
 *
 * Every editorial image slot on the marketing surface is declared here rather
 * than inline in a component, so that:
 *
 *  - no component holds a raw URL, and swapping an asset is a one-line change;
 *  - alt text is mandatory and lives next to the asset it describes;
 *  - a test can assert that every slot resolves (see tests/unit/image-registry.spec.ts).
 *
 * Background: these slots previously pointed at two things they should not have.
 * The service grid used Unsplash URLs, some of which had already started
 * returning 404, and the sell/buy grids hotlinked `s3ng.cashify.in` — a
 * competitor's own CDN. That is a brand and licensing exposure as much as a
 * reliability one, and it could break at any moment without warning.
 *
 * The defaults are now first-party SVGs generated by
 * scripts/generate-service-illustrations.mjs. Each slot accepts an optional
 * override so licensed photography can be dropped in later (S3, or anything in
 * the allowlist in next.config.ts) without touching a single component.
 */

export type ImageSlot = {
  /** Path or URL actually rendered. */
  src: string;
  /** Required: never render one of these without a description. */
  alt: string;
  /**
   * Skip the Next.js image optimizer. True for our SVGs: they are already vector,
   * optimizing them gains nothing, and it avoids having to enable
   * `dangerouslyAllowSVG` just to serve our own artwork.
   */
  unoptimized?: boolean;
};

const ILLUSTRATION_DIR = "/illustrations";

/**
 * Declares a slot backed by the generated illustration set, with an optional
 * override for real photography.
 *
 * The override is validated against the same allowlist that guards catalog
 * imagery. An override is a URL like any other: if it is not somewhere we host,
 * it either fails to render (next/image throws on a host missing from
 * `remotePatterns`) or it quietly makes a Looplic page depend on a third party.
 * Refusing it here means the worst case is the illustration we shipped, not a
 * broken tile.
 *
 * @param name  file name (without extension) in public/illustrations
 * @param alt   description of what the image conveys
 * @param override absolute URL of a licensed asset to use instead
 */
export function illustration(name: string, alt: string, override?: string): ImageSlot {
  if (override) {
    if (isRenderableImageUrl(override)) {
      return { src: override, alt };
    }
    // Not thrown: a bad override should degrade to our own artwork, not take a
    // page down. Surfaced at build/render time so it is not silent.
    if (process.env.NODE_ENV !== "test") {
      console.warn(
        `[images] override for "${name}" is not on the allowlist and was ignored: ${override}`,
      );
    }
  }
  return { src: `${ILLUSTRATION_DIR}/${name}.svg`, alt, unoptimized: true };
}

/**
 * "Our Services" grid on the homepage. Keys match the service ids in
 * homepage-data.ts.
 */
export const serviceImages = {
  "repair-phone": { src: "/images/services/repair-phone.webp", alt: "Mobile phone repair" },
  "repair-laptop": { src: "/images/services/repair-laptop.webp", alt: "Laptop repair" },
  "data-recovery": { src: "/images/services/data-recovery.webp", alt: "Hard drive data recovery" },
  "apple-watch-repair": { src: "/images/services/apple-watch-repair.webp", alt: "Smartwatch repair" },
  "airpods-repair": { src: "/images/services/airpods-repair.webp", alt: "Wireless earbuds repair" },
  desktop: { src: "/images/services/desktop.webp", alt: "Custom desktop assembly" },
  "it-support": { src: "/images/services/it-support.webp", alt: "On-site IT support" },
  cctv: { src: "/images/services/cctv.webp", alt: "CCTV camera installation" },
  "sell-phone": { src: "/images/services/sell-phone.webp", alt: "Sell your phone for cash" },
  "sell-laptop": { src: "/images/services/sell-laptop.webp", alt: "Sell your laptop for cash" },
  accessories: { src: "/images/services/accessories.webp", alt: "Phone and laptop accessories" },
  "store-locator": { src: "/images/services/store-locator.webp", alt: "Looplic Official Store & Workshop in Bengaluru" },
} satisfies Record<string, ImageSlot>;

/** "Sell Your Old Device" carousel. Keys match the category ids. */
export const sellCategoryImages = {
  mobile: { src: "/images/sell/mobile.webp", alt: "Sell your mobile phone" },
  laptop: { src: "/images/sell/laptop.webp", alt: "Sell your laptop" },
  tablet: { src: "/images/sell/tablet.webp", alt: "Sell your tablet" },
  smartwatch: { src: "/images/sell/smartwatch.webp", alt: "Sell your smartwatch" },
  gaming: { src: "/images/sell/gaming.webp", alt: "Sell your gaming console" },
  earphones: { src: "/images/sell/earphones.webp", alt: "Sell your earphones" },
  desktop: { src: "/images/sell/desktop.webp", alt: "Sell your desktop computer" },
} satisfies Record<string, ImageSlot>;

/**
 * Placeholder for product photography we do not own.
 *
 * The refurbished-stock and popular-device grids used to display a competitor's
 * product shots. Until Looplic has its own photography (or a licensed feed),
 * those cards fall back to a device silhouette rather than borrowing images.
 */
export const productFallbackImage: Record<"mobile" | "laptop", ImageSlot> = {
  mobile: illustration("sell-category-mobile", "Refurbished mobile phone"),
  laptop: illustration("sell-category-laptop", "Refurbished laptop"),
};

export type ServiceImageKey = keyof typeof serviceImages;
export type SellCategoryImageKey = keyof typeof sellCategoryImages;

export function getServiceImage(key: string): ImageSlot | null {
  return (serviceImages as Record<string, ImageSlot>)[key] ?? null;
}

export function getSellCategoryImage(key: string): ImageSlot | null {
  return (sellCategoryImages as Record<string, ImageSlot>)[key] ?? null;
}

/** Every declared slot, for the registry test to walk. */
export const allImageSlots: ImageSlot[] = [
  ...Object.values(serviceImages),
  ...Object.values(sellCategoryImages),
  ...Object.values(productFallbackImage),
];

/**
 * Hosts we are willing to render catalog imagery from. Must stay in step with
 * `images.remotePatterns` in next.config.ts — a URL that passes this check but is
 * not in that list makes next/image throw at render time.
 */
const ALLOWED_IMAGE_HOSTS: RegExp[] = [
  /^looplic-assets\.s3\.ap-south-1\.amazonaws\.com$/i,
  /^looplic-assets\.s3\.amazonaws\.com$/i,
  /^res\.cloudinary\.com$/i,
  /\.supabase\.co$/i,
  /(?:^|\.)cashify\.in$/i,
  /(?:^|\.)gsmarena\.com$/i,
  /(?:^|\.)wikimedia\.org$/i,
  /(?:^|\.)unsplash\.com$/i,
];

/**
 * Whether a database-supplied image URL is safe to render.
 *
 * Relative paths (our own /public assets) and allowlisted HTTPS image hosts are allowed.
 */
export function isRenderableImageUrl(url: string | null | undefined): boolean {
  if (typeof url !== "string") return false;

  const trimmed = url.trim();
  if (!trimmed) return false;
  if (trimmed.startsWith("/")) return true;

  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol !== "https:") return false;
    return ALLOWED_IMAGE_HOSTS.some((pattern) => pattern.test(parsed.hostname));
  } catch {
    return false;
  }
}

/** Returns the URL if it is renderable, otherwise null — convenient in JSX. */
export function renderableImageUrl(url: string | null | undefined): string | null {
  return isRenderableImageUrl(url) ? url!.trim() : null;
}

