import { and, desc, eq, or } from "drizzle-orm";

import { db } from "@/src/lib/db";
import { bookings, buybackBookings } from "@/src/lib/db/schema";
import {
  getCatalogSearchIndex,
  getRepairCategories,
  getRepairSubcategories,
  type CatalogServiceType,
} from "@/src/lib/data/catalog";
import {
  getBuybackQuestionSet,
  getBuybackVariants,
  type BuybackServiceType,
} from "@/src/lib/data/buyback";
import { brandOsSegment, computeBuybackQuote } from "@/src/lib/buyback/calc";
import { parseBookingLocation } from "@/src/lib/bookings";

// Server-side booking + pricing layer for the WhatsApp bot. This reuses the
// SAME catalog/pricing data the website uses and writes to the SAME `bookings`
// table (order_source = "whatsapp"), so WhatsApp bookings show up in admin Order
// Management exactly like website bookings. The booking_code is generated by the
// DB trigger (BEFORE INSERT) and read back, so codes match the website's format
// (MOB-YYMMDD-XXXXXX, LAP-…, CCT-…, etc.).

// Repair is only offered for mobile & laptop. Buyback additionally covers
// tablet / smartwatch / audio, handled separately.
export type RepairServiceType = "mobile" | "laptop";

const DB_SERVICE_TYPE: Record<RepairServiceType, string> = {
  mobile: "mobile_repair",
  laptop: "laptop_repair",
};

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

export type DeviceMatch = {
  modelId: string;
  modelName: string;
  brandId: string | null;
  brandName: string;
  seriesId: string | null;
  seriesName: string;
  serviceType: CatalogServiceType;
  label: string; // "Apple iPhone 12"
};

// Fuzzy-matches a free-text device query ("iphone 12", "galaxy s21") against the
// real catalog for a given service type. Works for repair (mobile/laptop) and
// buyback (also tablet/smartwatch/audio). Returns the best few candidates so the
// AI can confirm the exact model before pricing/booking.
export async function searchDevices(
  query: string,
  serviceType: CatalogServiceType = "mobile",
  limit = 6,
): Promise<DeviceMatch[]> {
  const q = norm(query);
  if (!q) return [];
  const terms = q.split(" ").filter(Boolean);

  let index;
  try {
    index = await getCatalogSearchIndex(serviceType);
  } catch {
    return [];
  }

  const scored = index.models
    .map((m) => {
      const hay = norm(`${m.brand_name} ${m.series_name} ${m.name}`);
      let score = 0;
      for (const t of terms) if (hay.includes(t)) score += t.length;
      // Bonus for the model name itself containing the whole query.
      if (norm(m.name).includes(q)) score += 5;
      return { m, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  // The search index only carries series_id on a model, so resolve the brand id
  // through the series index. Callers need both to be able to navigate BACK up
  // the catalogue (series picker, brand picker) after a text search jumped them
  // straight to a model.
  const brandIdBySeriesId = new Map<string, string>(
    index.series.map((s) => [s.id, s.brand_id] as [string, string]),
  );

  return scored.map(({ m }) => {
    // Catalog model names sometimes already include the brand ("Apple iPhone 12"),
    // so only prefix the brand when it isn't already there — avoids "Apple Apple …".
    const nameHasBrand = norm(m.name).startsWith(norm(m.brand_name));
    const label = (nameHasBrand ? m.name : `${m.brand_name} ${m.name}`).trim();
    return {
      modelId: m.id,
      modelName: m.name,
      brandId: brandIdBySeriesId.get(m.series_id) ?? null,
      brandName: m.brand_name,
      seriesId: m.series_id ?? null,
      seriesName: m.series_name,
      serviceType,
      label,
    };
  });
}

export type RepairPrice = {
  categoryId: string;
  categoryName: string;
  subcategoryId: string;
  subcategoryName: string;
  price: number;
};

// Returns the exact, model-specific repair prices for a model (same numbers the
// website shows). Only priced + visible services are returned.
export async function getRepairPricing(
  modelId: string,
  serviceType: RepairServiceType,
): Promise<RepairPrice[]> {
  const categories = await getRepairCategories(serviceType);
  if (categories.length === 0) return [];
  const categoryById = new Map(categories.map((c) => [c.id, c.name]));
  const subs = await getRepairSubcategories(
    categories.map((c) => c.id),
    modelId,
  );
  return subs
    .filter((s) => s.price_visible !== false && Number(s.price) > 0)
    .map((s) => ({
      categoryId: s.category_id,
      categoryName: categoryById.get(s.category_id) || "",
      subcategoryId: s.id,
      subcategoryName: s.name,
      price: Number(s.price),
    }));
}

export type RepairBookingInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  modelId: string;
  serviceType: RepairServiceType;
  repairCategoryId?: string | null;
  repairSubcategoryId?: string | null;
  location?: string | null;
  pincode?: string | null;
  scheduledDate?: string | null;
  timeSlot?: string | null;
  notes?: string | null;
};

// Creates a real repair booking row (order_source = "whatsapp"). Returns the
// DB-generated booking code. Throws on failure so the caller can tell the
// customer honestly rather than pretend it booked.
export async function createRepairBooking(input: RepairBookingInput): Promise<{ bookingCode: string }> {
  return createDeviceBooking({ ...input, dbServiceType: DB_SERVICE_TYPE[input.serviceType] });
}

export type DeviceBookingInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  modelId: string;
  /** Raw DB service type: mobile_repair | laptop_repair | screen_guard. */
  dbServiceType: string;
  repairCategoryId?: string | null;
  repairSubcategoryId?: string | null;
  /** Screen-guard flow only — the full guard_type string as stored in admin. */
  guardType?: string | null;
  location?: string | null;
  pincode?: string | null;
  scheduledDate?: string | null;
  timeSlot?: string | null;
  notes?: string | null;
};

// Creates a device booking (repair OR screen guard) exactly as the website does
// — same table, same columns, DB-generated booking code — with
// order_source = "whatsapp". The website writes guard_type for the screen-guard
// flow and repair_category_id/repair_subcategory_id for repairs; so do we.
export async function createDeviceBooking(input: DeviceBookingInput): Promise<{ bookingCode: string }> {
  const rows = await db
    .insert(bookings)
    .values({
      customerName: input.customerName,
      customerPhone: input.customerPhone,
      modelId: input.modelId,
      serviceType: input.dbServiceType,
      repairCategoryId: input.repairCategoryId ?? null,
      repairSubcategoryId: input.repairSubcategoryId ?? null,
      guardType: input.guardType ?? null,
      location: input.location ?? null,
      pincode: input.pincode ?? null,
      scheduledDate: input.scheduledDate ?? null,
      timeSlot: input.timeSlot ?? null,
      notes: input.notes ?? null,
      orderSource: "whatsapp",
      status: "pending",
    })
    .returning({ bookingCode: bookings.bookingCode });
  return { bookingCode: rows[0]?.bookingCode || "" };
}

export type ServiceBookingInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  // cctv | it_support | desktop_assembly | managed_it_services | wifi_network_installation
  serviceType: string;
  location?: string | null;
  pincode?: string | null;
  scheduledDate?: string | null;
  timeSlot?: string | null;
  cctvBrand?: string | null;
  cctvService?: string | null;
  notes?: string | null;
};

// Creates a real non-device service booking (CCTV / IT support / desktop / etc.),
// same table + code format as the website. These are enquiry-style bookings the
// team follows up to scope + quote.
export async function createServiceBooking(input: ServiceBookingInput): Promise<{ bookingCode: string }> {
  const rows = await db
    .insert(bookings)
    .values({
      customerName: input.customerName,
      customerPhone: input.customerPhone,
      modelId: null,
      serviceType: input.serviceType,
      location: input.location ?? null,
      pincode: input.pincode ?? null,
      scheduledDate: input.scheduledDate ?? null,
      timeSlot: input.timeSlot ?? null,
      cctvBrand: input.cctvBrand ?? null,
      cctvService: input.cctvService ?? null,
      notes: input.notes ?? null,
      orderSource: "whatsapp",
      status: "pending",
    })
    .returning({ bookingCode: bookings.bookingCode });
  return { bookingCode: rows[0]?.bookingCode || "" };
}

// ─── Saved details, tracking, reschedule, cancel ──────────────────────────────

export type SavedProfile = {
  name: string;
  phone: string;
  address: string;
  city: string;
  pincode: string;
};

// The website pre-fills the details step from the signed-in customer's saved
// profile. WhatsApp has no login, but the sender's number IS an identifier, so
// we pre-fill from their most recent booking on that number. Only ever used to
// OFFER the details back to the same number — never to share them elsewhere.
export async function getSavedProfile(phone: string): Promise<SavedProfile | null> {
  const candidates = phoneVariants(phone);
  if (candidates.length === 0) return null;
  try {
    const rows = await db
      .select({
        customerName: bookings.customerName,
        customerPhone: bookings.customerPhone,
        location: bookings.location,
        pincode: bookings.pincode,
      })
      .from(bookings)
      .where(or(...candidates.map((value) => eq(bookings.customerPhone, value))))
      .orderBy(desc(bookings.createdAt))
      .limit(1);

    const row = rows[0];
    if (!row) return null;

    // The website stores "address, city" in `location` (buildBookingLocation),
    // so the same parser reads it back.
    const { address, city } = parseBookingLocation(row.location);

    return {
      name: row.customerName || "",
      phone: row.customerPhone || "",
      address,
      city,
      pincode: row.pincode || "",
    };
  } catch (err) {
    console.error("[whatsapp:booking] getSavedProfile failed", err);
    return null;
  }
}

// The same number can be stored as 9876543210 or 919876543210 or +91… across
// website and WhatsApp bookings, so match on every plausible form.
function phoneVariants(phone: string): string[] {
  const digits = String(phone || "").replace(/[^\d]/g, "");
  if (digits.length < 10) return [];
  const local = digits.slice(-10);
  return Array.from(new Set([digits, local, `91${local}`, `+91${local}`, `0${local}`]));
}

export type TrackedBooking = {
  kind: "service" | "buyback";
  bookingCode: string;
  status: string;
  serviceType: string;
  scheduledDate: string | null;
  timeSlot: string | null;
  location: string | null;
  createdAt: Date | null;
  assignedRider: string | null;
  /** Buyback only. */
  quotedAmount: number | null;
  deviceLabel: string | null;
};

// Looks up one booking by its code across BOTH booking tables (service bookings
// use the DB trigger's MOB-/LAP-/CCT-… codes, buyback pickups use LBB-…).
// `waId` scopes the lookup to the sender's own number so a customer can't read
// somebody else's order by guessing a code.
export async function findBookingByCode(code: string, waId: string): Promise<TrackedBooking | null> {
  const normalized = String(code || "").trim().toUpperCase();
  if (!normalized) return null;
  const candidates = phoneVariants(waId);
  if (candidates.length === 0) return null;
  const phoneMatches = (value: string | null) =>
    candidates.includes(String(value || "").replace(/[^\d+]/g, ""));

  try {
    const serviceRows = await db
      .select()
      .from(bookings)
      .where(eq(bookings.bookingCode, normalized))
      .limit(1);
    const service = serviceRows[0];
    if (service) {
      if (!phoneMatches(service.customerPhone)) return null;
      return {
        kind: "service",
        bookingCode: service.bookingCode || normalized,
        status: service.status,
        serviceType: service.serviceType,
        scheduledDate: service.scheduledDate,
        timeSlot: service.timeSlot,
        location: service.location,
        createdAt: service.createdAt ?? null,
        assignedRider: service.assignedRider ?? null,
        quotedAmount: null,
        deviceLabel: null,
      };
    }

    const buybackRows = await db
      .select()
      .from(buybackBookings)
      .where(eq(buybackBookings.bookingCode, normalized))
      .limit(1);
    const buyback = buybackRows[0];
    if (buyback) {
      if (!phoneMatches(buyback.phone)) return null;
      return {
        kind: "buyback",
        bookingCode: buyback.bookingCode,
        status: buyback.status,
        serviceType: `${buyback.serviceType} buyback`,
        scheduledDate: buyback.pickupDate ?? null,
        timeSlot: buyback.timeSlot ?? null,
        location: buyback.address ?? null,
        createdAt: buyback.createdAt ?? null,
        assignedRider: null,
        quotedAmount: buyback.quotedAmount === null ? null : Number(buyback.quotedAmount),
        deviceLabel: [buyback.brandName, buyback.modelName, buyback.variantLabel]
          .filter(Boolean)
          .join(" "),
      };
    }
    return null;
  } catch (err) {
    console.error("[whatsapp:booking] findBookingByCode failed", err);
    return null;
  }
}

// The most recent bookings for the sender's number — powers "My orders".
export async function listRecentBookings(waId: string, limit = 5): Promise<TrackedBooking[]> {
  const candidates = phoneVariants(waId);
  if (candidates.length === 0) return [];
  try {
    const rows = await db
      .select()
      .from(bookings)
      .where(or(...candidates.map((value) => eq(bookings.customerPhone, value))))
      .orderBy(desc(bookings.createdAt))
      .limit(limit);
    return rows.map((row) => ({
      kind: "service" as const,
      bookingCode: row.bookingCode || "",
      status: row.status,
      serviceType: row.serviceType,
      scheduledDate: row.scheduledDate,
      timeSlot: row.timeSlot,
      location: row.location,
      createdAt: row.createdAt ?? null,
      assignedRider: row.assignedRider ?? null,
      quotedAmount: null,
      deviceLabel: null,
    }));
  } catch (err) {
    console.error("[whatsapp:booking] listRecentBookings failed", err);
    return [];
  }
}

// Statuses past the point where a customer may still self-serve. Anything the
// team has already acted on has to go through a human.
const LOCKED_STATUSES = new Set(["completed", "cancelled", "in_progress", "picked_up", "paid"]);

export function isSelfServiceEditable(status: string): boolean {
  return !LOCKED_STATUSES.has(String(status || "").toLowerCase());
}

export async function rescheduleBooking(
  code: string,
  waId: string,
  scheduledDate: string,
  timeSlot: string,
): Promise<{ ok: boolean; reason?: string }> {
  const booking = await findBookingByCode(code, waId);
  if (!booking) return { ok: false, reason: "not_found" };
  if (!isSelfServiceEditable(booking.status)) return { ok: false, reason: "locked" };

  try {
    if (booking.kind === "buyback") {
      await db
        .update(buybackBookings)
        .set({ pickupDate: scheduledDate, timeSlot, updatedAt: new Date() })
        .where(eq(buybackBookings.bookingCode, booking.bookingCode));
    } else {
      await db
        .update(bookings)
        .set({ scheduledDate, timeSlot })
        .where(eq(bookings.bookingCode, booking.bookingCode));
    }
    return { ok: true };
  } catch (err) {
    console.error("[whatsapp:booking] rescheduleBooking failed", err);
    return { ok: false, reason: "error" };
  }
}

export async function cancelBooking(
  code: string,
  waId: string,
  reason?: string | null,
): Promise<{ ok: boolean; reason?: string }> {
  const booking = await findBookingByCode(code, waId);
  if (!booking) return { ok: false, reason: "not_found" };
  if (!isSelfServiceEditable(booking.status)) return { ok: false, reason: "locked" };

  const note = `Cancelled by customer on WhatsApp${reason ? `: ${reason}` : ""}`;
  try {
    if (booking.kind === "buyback") {
      await db
        .update(buybackBookings)
        .set({ status: "cancelled", updatedAt: new Date() })
        .where(eq(buybackBookings.bookingCode, booking.bookingCode));
    } else {
      const current = await db
        .select({ notes: bookings.notes })
        .from(bookings)
        .where(eq(bookings.bookingCode, booking.bookingCode))
        .limit(1);
      const notes = [current[0]?.notes, note].filter(Boolean).join("\n\n");
      await db
        .update(bookings)
        .set({ status: "cancelled", notes })
        .where(and(eq(bookings.bookingCode, booking.bookingCode)));
    }
    return { ok: true };
  } catch (err) {
    console.error("[whatsapp:booking] cancelBooking failed", err);
    return { ok: false, reason: "error" };
  }
}

// ─── Buyback (sell) pricing — uses the SAME engine as the website Sell flow ────

export type SellOption = { id: string; label: string };
export type SellQuestion = { id: string; title: string; type: "single" | "multi"; options: SellOption[] };
export type SellDeviceOptions = {
  priced: boolean; // false when the model has no buyback price configured
  variants: { id: string; label: string }[]; // storage/spec choices (label may be "")
  questions: SellQuestion[]; // condition questions to ask the customer
};

// Returns the variants + condition questions the customer must answer to get an
// exact buyback quote (the option EFFECTS/amounts are intentionally hidden — the
// bot only needs labels to present choices; the quote is computed server-side).
export async function getBuybackDeviceOptions(
  modelId: string,
  deviceType: BuybackServiceType,
  brandName: string,
): Promise<SellDeviceOptions> {
  const variants = await getBuybackVariants(modelId);
  const seg = brandOsSegment(brandName);
  const qset = await getBuybackQuestionSet(deviceType, seg);
  return {
    priced: variants.length > 0,
    variants: variants.map((v) => ({ id: v.id, label: v.label })),
    questions: qset.questions.map((q) => ({
      id: q.id,
      title: q.title,
      type: q.question_type,
      options: (qset.optionsByQuestion[q.id] || []).map((o) => ({ id: o.id, label: o.label })),
    })),
  };
}

// Computes the exact buyback estimate for a model/variant + the customer's
// condition answers — byte-for-byte the same number the website Sell flow shows
// (same computeBuybackQuote engine, prices managed in admin). `selected` maps
// questionId -> chosen optionId(s). Returns null when the model is unpriced.
export async function computeBuybackEstimate(
  modelId: string,
  deviceType: BuybackServiceType,
  brandName: string,
  variantId: string | null,
  selected: Record<string, string[]>,
): Promise<{ basePrice: number; finalQuote: number; variantLabel: string } | null> {
  const variants = await getBuybackVariants(modelId);
  if (variants.length === 0) return null;
  const variant = variants.find((v) => v.id === variantId) ?? variants[0];
  const seg = brandOsSegment(brandName);
  const qset = await getBuybackQuestionSet(deviceType, seg);
  const { basePrice, finalQuote } = computeBuybackQuote(
    variant.basePrice,
    qset.questions,
    qset.optionsByQuestion,
    selected,
  );
  return { basePrice, finalQuote, variantLabel: variant.label };
}

export type BuybackPickupInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  brandName: string;
  modelName: string;
  variantLabel?: string | null;
  serviceType?: string | null; // mobile | laptop | tablet | ...
  quotedAmount?: number | null; // the estimate from computeBuybackEstimate
  quoteBreakdown?: string | null;
  address?: string | null;
  pickupDate?: string | null;
  timeSlot?: string | null;
  notes?: string | null;
};

// Books a device buyback pickup (reuses the same buyback_bookings table as the
// website Sell flow), recording the estimate. The final buyback price is
// confirmed at inspection — even on the website the quote is an estimate until
// the device is physically checked.
export async function createBuybackPickup(input: BuybackPickupInput): Promise<{ bookingCode: string }> {
  const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
  let suffix = "";
  for (let i = 0; i < 6; i++) suffix += alphabet[Math.floor(Math.random() * alphabet.length)];
  const bookingCode = `LBB-${suffix}`;

  await db.insert(buybackBookings).values({
    bookingCode,
    serviceType: input.serviceType || "mobile",
    brandName: input.brandName,
    modelName: input.modelName,
    variantLabel: input.variantLabel ?? null,
    quotedAmount:
      input.quotedAmount === null || input.quotedAmount === undefined ? null : String(Math.round(input.quotedAmount)),
    quoteBreakdown: input.quoteBreakdown ?? null,
    customerName: input.customerName,
    phone: input.customerPhone,
    address: input.address ?? null,
    pickupDate: input.pickupDate ?? null,
    timeSlot: input.timeSlot ?? null,
    status: "pending",
  });
  return { bookingCode };
}
