import { db } from "@/src/lib/db";
import { bookings, buybackBookings } from "@/src/lib/db/schema";
import {
  getCatalogSearchIndex,
  getRepairCategories,
  getRepairSubcategories,
  type CatalogServiceType,
} from "@/src/lib/data/catalog";
import {
  getBuybackQuestionSet,
  getBuybackVariants,
  type BuybackServiceType,
} from "@/src/lib/data/buyback";
import { brandOsSegment, computeBuybackQuote } from "@/src/lib/buyback/calc";

// Server-side booking + pricing layer for the WhatsApp bot. This reuses the
// SAME catalog/pricing data the website uses and writes to the SAME `bookings`
// table (order_source = "whatsapp"), so WhatsApp bookings show up in admin Order
// Management exactly like website bookings. The booking_code is generated by the
// DB trigger (BEFORE INSERT) and read back, so codes match the website's format
// (MOB-YYMMDD-XXXXXX, LAP-…, CCT-…, etc.).

// Repair is only offered for mobile & laptop. Buyback additionally covers
// tablet / smartwatch / audio, handled separately.
export type RepairServiceType = "mobile" | "laptop";

const DB_SERVICE_TYPE: Record<RepairServiceType, string> = {
  mobile: "mobile_repair",
  laptop: "laptop_repair",
};

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

export type DeviceMatch = {
  modelId: string;
  modelName: string;
  brandName: string;
  seriesName: string;
  serviceType: CatalogServiceType;
  label: string; // "Apple iPhone 12"
};

// Fuzzy-matches a free-text device query ("iphone 12", "galaxy s21") against the
// real catalog for a given service type. Works for repair (mobile/laptop) and
// buyback (also tablet/smartwatch/audio). Returns the best few candidates so the
// AI can confirm the exact model before pricing/booking.
export async function searchDevices(
  query: string,
  serviceType: CatalogServiceType = "mobile",
  limit = 6,
): Promise<DeviceMatch[]> {
  const q = norm(query);
  if (!q) return [];
  const terms = q.split(" ").filter(Boolean);

  let index;
  try {
    index = await getCatalogSearchIndex(serviceType);
  } catch {
    return [];
  }

  const scored = index.models
    .map((m) => {
      const hay = norm(`${m.brand_name} ${m.series_name} ${m.name}`);
      let score = 0;
      for (const t of terms) if (hay.includes(t)) score += t.length;
      // Bonus for the model name itself containing the whole query.
      if (norm(m.name).includes(q)) score += 5;
      return { m, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);

  return scored.map(({ m }) => ({
    modelId: m.id,
    modelName: m.name,
    brandName: m.brand_name,
    seriesName: m.series_name,
    serviceType,
    label: `${m.brand_name} ${m.name}`.trim(),
  }));
}

export type RepairPrice = {
  categoryId: string;
  categoryName: string;
  subcategoryId: string;
  subcategoryName: string;
  price: number;
};

// Returns the exact, model-specific repair prices for a model (same numbers the
// website shows). Only priced + visible services are returned.
export async function getRepairPricing(
  modelId: string,
  serviceType: RepairServiceType,
): Promise<RepairPrice[]> {
  const categories = await getRepairCategories(serviceType);
  if (categories.length === 0) return [];
  const categoryById = new Map(categories.map((c) => [c.id, c.name]));
  const subs = await getRepairSubcategories(
    categories.map((c) => c.id),
    modelId,
  );
  return subs
    .filter((s) => s.price_visible !== false && Number(s.price) > 0)
    .map((s) => ({
      categoryId: s.category_id,
      categoryName: categoryById.get(s.category_id) || "",
      subcategoryId: s.id,
      subcategoryName: s.name,
      price: Number(s.price),
    }));
}

export type RepairBookingInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  modelId: string;
  serviceType: RepairServiceType;
  repairCategoryId?: string | null;
  repairSubcategoryId?: string | null;
  location?: string | null;
  pincode?: string | null;
  scheduledDate?: string | null;
  timeSlot?: string | null;
  notes?: string | null;
};

// Creates a real repair booking row (order_source = "whatsapp"). Returns the
// DB-generated booking code. Throws on failure so the caller can tell the
// customer honestly rather than pretend it booked.
export async function createRepairBooking(input: RepairBookingInput): Promise<{ bookingCode: string }> {
  const rows = await db
    .insert(bookings)
    .values({
      customerName: input.customerName,
      customerPhone: input.customerPhone,
      modelId: input.modelId,
      serviceType: DB_SERVICE_TYPE[input.serviceType],
      repairCategoryId: input.repairCategoryId ?? null,
      repairSubcategoryId: input.repairSubcategoryId ?? null,
      location: input.location ?? null,
      pincode: input.pincode ?? null,
      scheduledDate: input.scheduledDate ?? null,
      timeSlot: input.timeSlot ?? null,
      notes: input.notes ?? null,
      orderSource: "whatsapp",
      status: "pending",
    })
    .returning({ bookingCode: bookings.bookingCode });
  return { bookingCode: rows[0]?.bookingCode || "" };
}

export type ServiceBookingInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  // cctv | it_support | desktop_assembly | managed_it_services | wifi_network_installation
  serviceType: string;
  location?: string | null;
  pincode?: string | null;
  scheduledDate?: string | null;
  timeSlot?: string | null;
  cctvBrand?: string | null;
  cctvService?: string | null;
  notes?: string | null;
};

// Creates a real non-device service booking (CCTV / IT support / desktop / etc.),
// same table + code format as the website. These are enquiry-style bookings the
// team follows up to scope + quote.
export async function createServiceBooking(input: ServiceBookingInput): Promise<{ bookingCode: string }> {
  const rows = await db
    .insert(bookings)
    .values({
      customerName: input.customerName,
      customerPhone: input.customerPhone,
      modelId: null,
      serviceType: input.serviceType,
      location: input.location ?? null,
      pincode: input.pincode ?? null,
      scheduledDate: input.scheduledDate ?? null,
      timeSlot: input.timeSlot ?? null,
      cctvBrand: input.cctvBrand ?? null,
      cctvService: input.cctvService ?? null,
      notes: input.notes ?? null,
      orderSource: "whatsapp",
      status: "pending",
    })
    .returning({ bookingCode: bookings.bookingCode });
  return { bookingCode: rows[0]?.bookingCode || "" };
}

// ─── Buyback (sell) pricing — uses the SAME engine as the website Sell flow ────

export type SellOption = { id: string; label: string };
export type SellQuestion = { id: string; title: string; type: "single" | "multi"; options: SellOption[] };
export type SellDeviceOptions = {
  priced: boolean; // false when the model has no buyback price configured
  variants: { id: string; label: string }[]; // storage/spec choices (label may be "")
  questions: SellQuestion[]; // condition questions to ask the customer
};

// Returns the variants + condition questions the customer must answer to get an
// exact buyback quote (the option EFFECTS/amounts are intentionally hidden — the
// bot only needs labels to present choices; the quote is computed server-side).
export async function getBuybackDeviceOptions(
  modelId: string,
  deviceType: BuybackServiceType,
  brandName: string,
): Promise<SellDeviceOptions> {
  const variants = await getBuybackVariants(modelId);
  const seg = brandOsSegment(brandName);
  const qset = await getBuybackQuestionSet(deviceType, seg);
  return {
    priced: variants.length > 0,
    variants: variants.map((v) => ({ id: v.id, label: v.label })),
    questions: qset.questions.map((q) => ({
      id: q.id,
      title: q.title,
      type: q.question_type,
      options: (qset.optionsByQuestion[q.id] || []).map((o) => ({ id: o.id, label: o.label })),
    })),
  };
}

// Computes the exact buyback estimate for a model/variant + the customer's
// condition answers — byte-for-byte the same number the website Sell flow shows
// (same computeBuybackQuote engine, prices managed in admin). `selected` maps
// questionId -> chosen optionId(s). Returns null when the model is unpriced.
export async function computeBuybackEstimate(
  modelId: string,
  deviceType: BuybackServiceType,
  brandName: string,
  variantId: string | null,
  selected: Record<string, string[]>,
): Promise<{ basePrice: number; finalQuote: number; variantLabel: string } | null> {
  const variants = await getBuybackVariants(modelId);
  if (variants.length === 0) return null;
  const variant = variants.find((v) => v.id === variantId) ?? variants[0];
  const seg = brandOsSegment(brandName);
  const qset = await getBuybackQuestionSet(deviceType, seg);
  const { basePrice, finalQuote } = computeBuybackQuote(
    variant.basePrice,
    qset.questions,
    qset.optionsByQuestion,
    selected,
  );
  return { basePrice, finalQuote, variantLabel: variant.label };
}

export type BuybackPickupInput = {
  waId: string;
  customerName: string;
  customerPhone: string;
  brandName: string;
  modelName: string;
  variantLabel?: string | null;
  serviceType?: string | null; // mobile | laptop | tablet | ...
  quotedAmount?: number | null; // the estimate from computeBuybackEstimate
  quoteBreakdown?: string | null;
  address?: string | null;
  pickupDate?: string | null;
  timeSlot?: string | null;
  notes?: string | null;
};

// Books a device buyback pickup (reuses the same buyback_bookings table as the
// website Sell flow), recording the estimate. The final buyback price is
// confirmed at inspection — even on the website the quote is an estimate until
// the device is physically checked.
export async function createBuybackPickup(input: BuybackPickupInput): Promise<{ bookingCode: string }> {
  const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
  let suffix = "";
  for (let i = 0; i < 6; i++) suffix += alphabet[Math.floor(Math.random() * alphabet.length)];
  const bookingCode = `LBB-${suffix}`;

  await db.insert(buybackBookings).values({
    bookingCode,
    serviceType: input.serviceType || "mobile",
    brandName: input.brandName,
    modelName: input.modelName,
    variantLabel: input.variantLabel ?? null,
    quotedAmount:
      input.quotedAmount === null || input.quotedAmount === undefined ? null : String(Math.round(input.quotedAmount)),
    quoteBreakdown: input.quoteBreakdown ?? null,
    customerName: input.customerName,
    phone: input.customerPhone,
    address: input.address ?? null,
    pickupDate: input.pickupDate ?? null,
    timeSlot: input.timeSlot ?? null,
    status: "pending",
  });
  return { bookingCode };
}
