create unique index if not exists brands_service_type_slug_key
  on public.brands (service_type, slug);

create unique index if not exists series_brand_slug_key
  on public.series (brand_id, slug);

create unique index if not exists models_series_slug_key
  on public.models (series_id, slug);

with seed_brand(name, slug, letter, gradient, sort_order) as (
  values
    ('Dell', 'dell', 'D', 'from-sky-500 to-blue-600', 1),
    ('HP', 'hp', 'HP', 'from-indigo-500 to-sky-500', 2),
    ('Lenovo', 'lenovo', 'L', 'from-red-500 to-rose-600', 3),
    ('Asus', 'asus', 'A', 'from-blue-600 to-indigo-700', 4),
    ('Acer', 'acer', 'A', 'from-emerald-500 to-lime-600', 5),
    ('MSI', 'msi', 'M', 'from-red-600 to-zinc-900', 6),
    ('Apple', 'apple', 'A', 'from-gray-700 to-gray-900', 7),
    ('Microsoft', 'microsoft', 'M', 'from-sky-600 to-cyan-500', 8),
    ('Samsung', 'samsung', 'S', 'from-blue-500 to-blue-700', 9),
    ('Razer', 'razer', 'R', 'from-lime-500 to-green-700', 10),
    ('LG', 'lg', 'LG', 'from-rose-500 to-pink-600', 11),
    ('Gigabyte', 'gigabyte', 'G', 'from-orange-500 to-red-600', 12),
    ('Huawei', 'huawei', 'H', 'from-red-500 to-orange-600', 13),
    ('Xiaomi', 'xiaomi', 'Mi', 'from-orange-400 to-orange-600', 14),
    ('Realme', 'realme', 'R', 'from-yellow-400 to-yellow-600', 15),
    ('Infinix', 'infinix', 'I', 'from-green-500 to-emerald-600', 16),
    ('Honor', 'honor', 'H', 'from-blue-500 to-cyan-600', 17),
    ('Framework', 'framework', 'F', 'from-gray-600 to-slate-900', 18),
    ('Avita', 'avita', 'A', 'from-fuchsia-500 to-pink-600', 19),
    ('Dynabook', 'dynabook', 'D', 'from-blue-700 to-slate-900', 20),
    ('Fujitsu', 'fujitsu', 'F', 'from-red-600 to-gray-900', 21),
    ('VAIO', 'vaio', 'V', 'from-violet-500 to-slate-800', 22),
    ('Chuwi', 'chuwi', 'C', 'from-cyan-500 to-blue-600', 23)
)
insert into public.brands (name, slug, letter, gradient, service_type, sort_order)
select name, slug, letter, gradient, 'laptop', sort_order
from seed_brand
on conflict (service_type, slug) do update
set name = excluded.name,
    letter = excluded.letter,
    gradient = excluded.gradient,
    sort_order = excluded.sort_order;

create temp table laptop_series_seed (
  brand_slug text not null,
  series_name text not null,
  series_slug text not null
) on commit drop;

insert into laptop_series_seed (brand_slug, series_name, series_slug)
values
  ('acer', 'Aspire', 'aspire'),
  ('acer', 'Swift', 'swift'),
  ('acer', 'Nitro', 'nitro'),
  ('acer', 'Predator', 'predator'),
  ('acer', 'TravelMate', 'travelmate'),
  ('acer', 'Extensa', 'extensa'),
  ('acer', 'Chromebook', 'chromebook'),
  ('apple', 'MacBook Air', 'macbook-air'),
  ('apple', 'MacBook Pro', 'macbook-pro'),
  ('asus', 'Vivobook', 'vivobook'),
  ('asus', 'Zenbook', 'zenbook'),
  ('asus', 'ROG', 'rog'),
  ('asus', 'TUF Gaming', 'tuf-gaming'),
  ('asus', 'ExpertBook', 'expertbook'),
  ('asus', 'ProArt', 'proart'),
  ('asus', 'Chromebook', 'chromebook'),
  ('avita', 'Liber', 'liber'),
  ('avita', 'Pura', 'pura'),
  ('avita', 'Essential', 'essential'),
  ('avita', 'Admiror', 'admiror'),
  ('chuwi', 'HeroBook', 'herobook'),
  ('chuwi', 'CoreBook', 'corebook'),
  ('chuwi', 'GemiBook', 'gemibook'),
  ('chuwi', 'MiniBook', 'minibook'),
  ('dell', 'Inspiron', 'inspiron'),
  ('dell', 'XPS', 'xps'),
  ('dell', 'Latitude', 'latitude'),
  ('dell', 'Precision', 'precision'),
  ('dell', 'Alienware', 'alienware'),
  ('dell', 'G Series', 'g-series'),
  ('dell', 'Vostro', 'vostro'),
  ('dynabook', 'Satellite Pro', 'satellite-pro'),
  ('dynabook', 'Tecra', 'tecra'),
  ('dynabook', 'Portege', 'portege'),
  ('framework', 'Framework Laptop', 'framework-laptop'),
  ('fujitsu', 'LIFEBOOK', 'lifebook'),
  ('fujitsu', 'CELSIUS', 'celsius'),
  ('gigabyte', 'AORUS', 'aorus'),
  ('gigabyte', 'AERO', 'aero'),
  ('gigabyte', 'G Series', 'g-series'),
  ('gigabyte', 'U Series', 'u-series'),
  ('honor', 'MagicBook', 'magicbook'),
  ('hp', 'HP Laptop', 'hp-laptop'),
  ('hp', 'Pavilion', 'pavilion'),
  ('hp', 'Envy', 'envy'),
  ('hp', 'Spectre', 'spectre'),
  ('hp', 'OmniBook', 'omnibook'),
  ('hp', 'EliteBook', 'elitebook'),
  ('hp', 'ProBook', 'probook'),
  ('hp', 'ZBook', 'zbook'),
  ('hp', 'OMEN', 'omen'),
  ('hp', 'Victus', 'victus'),
  ('hp', 'Chromebook', 'chromebook'),
  ('huawei', 'MateBook D', 'matebook-d'),
  ('huawei', 'MateBook', 'matebook'),
  ('huawei', 'MateBook X', 'matebook-x'),
  ('huawei', 'MateBook E', 'matebook-e'),
  ('infinix', 'INBook', 'inbook'),
  ('infinix', 'ZeroBook', 'zerobook'),
  ('infinix', 'GT Book', 'gt-book'),
  ('lenovo', 'IdeaPad', 'ideapad'),
  ('lenovo', 'Yoga', 'yoga'),
  ('lenovo', 'ThinkPad', 'thinkpad'),
  ('lenovo', 'ThinkBook', 'thinkbook'),
  ('lenovo', 'Legion', 'legion'),
  ('lenovo', 'LOQ', 'loq'),
  ('lenovo', 'Chromebook', 'chromebook'),
  ('lg', 'Gram', 'gram'),
  ('lg', 'Gram Pro', 'gram-pro'),
  ('lg', 'Gram 2-in-1', 'gram-2-in-1'),
  ('microsoft', 'Surface Laptop', 'surface-laptop'),
  ('microsoft', 'Surface Pro', 'surface-pro'),
  ('microsoft', 'Surface Laptop Studio', 'surface-laptop-studio'),
  ('microsoft', 'Surface Laptop Go', 'surface-laptop-go'),
  ('msi', 'Modern', 'modern'),
  ('msi', 'Prestige', 'prestige'),
  ('msi', 'Summit', 'summit'),
  ('msi', 'Creator', 'creator'),
  ('msi', 'Katana', 'katana'),
  ('msi', 'Cyborg', 'cyborg'),
  ('msi', 'Thin', 'thin'),
  ('msi', 'Stealth', 'stealth'),
  ('msi', 'Raider', 'raider'),
  ('msi', 'Vector', 'vector'),
  ('msi', 'Titan', 'titan'),
  ('razer', 'Blade', 'blade'),
  ('realme', 'Book', 'book'),
  ('samsung', 'Galaxy Book', 'galaxy-book'),
  ('vaio', 'SX', 'sx'),
  ('vaio', 'FE', 'fe'),
  ('vaio', 'FH', 'fh'),
  ('xiaomi', 'Mi Notebook', 'mi-notebook'),
  ('xiaomi', 'RedmiBook', 'redmibook'),
  ('xiaomi', 'Xiaomi Book', 'xiaomi-book');

with resolved_series as (
  select brand.id as brand_id, seed.series_name, seed.series_slug
  from laptop_series_seed seed
  join public.brands brand
    on brand.service_type = 'laptop'
   and brand.slug = seed.brand_slug
)
insert into public.series (brand_id, name, slug)
select brand_id, series_name, series_slug
from resolved_series
on conflict (brand_id, slug) do update
set name = excluded.name;

create temp table laptop_model_seed (
  brand_slug text not null,
  series_slug text not null,
  model_name text not null,
  model_slug text not null
) on commit drop;

insert into laptop_model_seed (brand_slug, series_slug, model_name, model_slug)
values
  ('acer', 'aspire', 'Aspire 3', 'aspire-3'),
  ('acer', 'aspire', 'Aspire 5', 'aspire-5'),
  ('acer', 'aspire', 'Aspire 7', 'aspire-7'),
  ('acer', 'aspire', 'Aspire Vero', 'aspire-vero'),
  ('acer', 'swift', 'Swift Go 14', 'swift-go-14'),
  ('acer', 'swift', 'Swift Go 16', 'swift-go-16'),
  ('acer', 'swift', 'Swift X 14', 'swift-x-14'),
  ('acer', 'swift', 'Swift Edge 16', 'swift-edge-16'),
  ('acer', 'nitro', 'Nitro V 15', 'nitro-v-15'),
  ('acer', 'nitro', 'Nitro V 16', 'nitro-v-16'),
  ('acer', 'nitro', 'Nitro 16', 'nitro-16'),
  ('acer', 'nitro', 'Nitro 17', 'nitro-17'),
  ('acer', 'predator', 'Predator Helios Neo 16', 'predator-helios-neo-16'),
  ('acer', 'predator', 'Predator Helios 16', 'predator-helios-16'),
  ('acer', 'predator', 'Predator Helios 18', 'predator-helios-18'),
  ('acer', 'predator', 'Predator Triton 14', 'predator-triton-14'),
  ('acer', 'travelmate', 'TravelMate P2', 'travelmate-p2'),
  ('acer', 'travelmate', 'TravelMate P4', 'travelmate-p4'),
  ('acer', 'travelmate', 'TravelMate P6', 'travelmate-p6'),
  ('acer', 'extensa', 'Extensa 15', 'extensa-15'),
  ('acer', 'chromebook', 'Chromebook Spin 514', 'chromebook-spin-514'),
  ('acer', 'chromebook', 'Chromebook Plus 515', 'chromebook-plus-515'),
  ('apple', 'macbook-air', 'MacBook Air 13-inch', 'macbook-air-13-inch'),
  ('apple', 'macbook-air', 'MacBook Air 15-inch', 'macbook-air-15-inch'),
  ('apple', 'macbook-pro', 'MacBook Pro 14-inch', 'macbook-pro-14-inch'),
  ('apple', 'macbook-pro', 'MacBook Pro 16-inch', 'macbook-pro-16-inch'),
  ('asus', 'vivobook', 'Vivobook Go 14', 'vivobook-go-14'),
  ('asus', 'vivobook', 'Vivobook Go 15', 'vivobook-go-15'),
  ('asus', 'vivobook', 'Vivobook S 14', 'vivobook-s-14'),
  ('asus', 'vivobook', 'Vivobook S 15', 'vivobook-s-15'),
  ('asus', 'vivobook', 'Vivobook S 16', 'vivobook-s-16'),
  ('asus', 'vivobook', 'Vivobook Pro 15', 'vivobook-pro-15'),
  ('asus', 'vivobook', 'Vivobook Pro 16', 'vivobook-pro-16'),
  ('asus', 'zenbook', 'Zenbook 14', 'zenbook-14'),
  ('asus', 'zenbook', 'Zenbook S 13 OLED', 'zenbook-s-13-oled'),
  ('asus', 'zenbook', 'Zenbook S 14', 'zenbook-s-14'),
  ('asus', 'zenbook', 'Zenbook Duo', 'zenbook-duo'),
  ('asus', 'zenbook', 'Zenbook Pro 14', 'zenbook-pro-14'),
  ('asus', 'rog', 'ROG Zephyrus G14', 'rog-zephyrus-g14'),
  ('asus', 'rog', 'ROG Zephyrus G16', 'rog-zephyrus-g16'),
  ('asus', 'rog', 'ROG Strix G16', 'rog-strix-g16'),
  ('asus', 'rog', 'ROG Strix G18', 'rog-strix-g18'),
  ('asus', 'rog', 'ROG Flow X13', 'rog-flow-x13'),
  ('asus', 'rog', 'ROG Flow Z13', 'rog-flow-z13'),
  ('asus', 'tuf-gaming', 'TUF Gaming A15', 'tuf-gaming-a15'),
  ('asus', 'tuf-gaming', 'TUF Gaming A16', 'tuf-gaming-a16'),
  ('asus', 'tuf-gaming', 'TUF Gaming F15', 'tuf-gaming-f15'),
  ('asus', 'tuf-gaming', 'TUF Gaming F16', 'tuf-gaming-f16'),
  ('asus', 'expertbook', 'ExpertBook B1', 'expertbook-b1'),
  ('asus', 'expertbook', 'ExpertBook B3', 'expertbook-b3'),
  ('asus', 'expertbook', 'ExpertBook B5', 'expertbook-b5'),
  ('asus', 'expertbook', 'ExpertBook B9', 'expertbook-b9'),
  ('asus', 'proart', 'ProArt P16', 'proart-p16'),
  ('asus', 'proart', 'ProArt Studiobook 16', 'proart-studiobook-16'),
  ('asus', 'chromebook', 'Chromebook CX34', 'chromebook-cx34'),
  ('asus', 'chromebook', 'Chromebook Flip CX5', 'chromebook-flip-cx5'),
  ('avita', 'liber', 'Avita Liber 14', 'avita-liber-14'),
  ('avita', 'pura', 'Avita Pura', 'avita-pura'),
  ('avita', 'essential', 'Avita Essential', 'avita-essential'),
  ('avita', 'admiror', 'Avita Admiror', 'avita-admiror'),
  ('chuwi', 'herobook', 'HeroBook Pro', 'herobook-pro'),
  ('chuwi', 'corebook', 'CoreBook X', 'corebook-x'),
  ('chuwi', 'gemibook', 'GemiBook Plus', 'gemibook-plus'),
  ('chuwi', 'minibook', 'MiniBook X', 'minibook-x'),
  ('dell', 'inspiron', 'Inspiron 14', 'inspiron-14'),
  ('dell', 'inspiron', 'Inspiron 15', 'inspiron-15'),
  ('dell', 'inspiron', 'Inspiron 16', 'inspiron-16'),
  ('dell', 'inspiron', 'Inspiron 14 2-in-1', 'inspiron-14-2-in-1'),
  ('dell', 'xps', 'XPS 13', 'xps-13'),
  ('dell', 'xps', 'XPS 14', 'xps-14'),
  ('dell', 'xps', 'XPS 16', 'xps-16'),
  ('dell', 'latitude', 'Latitude 3340', 'latitude-3340'),
  ('dell', 'latitude', 'Latitude 5440', 'latitude-5440'),
  ('dell', 'latitude', 'Latitude 7440', 'latitude-7440'),
  ('dell', 'latitude', 'Latitude 9450 2-in-1', 'latitude-9450-2-in-1'),
  ('dell', 'precision', 'Precision 3490', 'precision-3490'),
  ('dell', 'precision', 'Precision 5490', 'precision-5490'),
  ('dell', 'precision', 'Precision 5690', 'precision-5690'),
  ('dell', 'precision', 'Precision 7780', 'precision-7780'),
  ('dell', 'alienware', 'Alienware m16', 'alienware-m16'),
  ('dell', 'alienware', 'Alienware x16', 'alienware-x16'),
  ('dell', 'alienware', 'Alienware m18', 'alienware-m18'),
  ('dell', 'g-series', 'Dell G15', 'dell-g15'),
  ('dell', 'g-series', 'Dell G16', 'dell-g16'),
  ('dell', 'vostro', 'Vostro 14', 'vostro-14'),
  ('dell', 'vostro', 'Vostro 15', 'vostro-15'),
  ('dynabook', 'satellite-pro', 'Satellite Pro C40', 'satellite-pro-c40'),
  ('dynabook', 'satellite-pro', 'Satellite Pro C50', 'satellite-pro-c50'),
  ('dynabook', 'tecra', 'Tecra A40', 'tecra-a40'),
  ('dynabook', 'tecra', 'Tecra A50', 'tecra-a50'),
  ('dynabook', 'portege', 'Portege X30', 'portege-x30'),
  ('dynabook', 'portege', 'Portege X40', 'portege-x40'),
  ('framework', 'framework-laptop', 'Framework Laptop 13', 'framework-laptop-13'),
  ('framework', 'framework-laptop', 'Framework Laptop 16', 'framework-laptop-16'),
  ('fujitsu', 'lifebook', 'LIFEBOOK U Series', 'lifebook-u-series'),
  ('fujitsu', 'lifebook', 'LIFEBOOK E Series', 'lifebook-e-series'),
  ('fujitsu', 'lifebook', 'LIFEBOOK A Series', 'lifebook-a-series'),
  ('fujitsu', 'celsius', 'CELSIUS H Series', 'celsius-h-series'),
  ('gigabyte', 'aorus', 'AORUS 15', 'aorus-15'),
  ('gigabyte', 'aorus', 'AORUS 16', 'aorus-16'),
  ('gigabyte', 'aorus', 'AORUS 17', 'aorus-17'),
  ('gigabyte', 'aero', 'AERO 14', 'aero-14'),
  ('gigabyte', 'aero', 'AERO 16', 'aero-16'),
  ('gigabyte', 'g-series', 'G5', 'g5'),
  ('gigabyte', 'g-series', 'G6', 'g6'),
  ('gigabyte', 'u-series', 'U4', 'u4'),
  ('honor', 'magicbook', 'MagicBook X14', 'magicbook-x14'),
  ('honor', 'magicbook', 'MagicBook X16', 'magicbook-x16'),
  ('honor', 'magicbook', 'MagicBook 14', 'magicbook-14'),
  ('honor', 'magicbook', 'MagicBook 16 Pro', 'magicbook-16-pro'),
  ('hp', 'hp-laptop', 'HP 14', 'hp-14'),
  ('hp', 'hp-laptop', 'HP 15', 'hp-15'),
  ('hp', 'hp-laptop', 'HP 17', 'hp-17'),
  ('hp', 'pavilion', 'Pavilion 14', 'pavilion-14'),
  ('hp', 'pavilion', 'Pavilion 15', 'pavilion-15'),
  ('hp', 'pavilion', 'Pavilion x360 14', 'pavilion-x360-14'),
  ('hp', 'envy', 'Envy 14', 'envy-14'),
  ('hp', 'envy', 'Envy 16', 'envy-16'),
  ('hp', 'envy', 'Envy x360 14', 'envy-x360-14'),
  ('hp', 'spectre', 'Spectre x360 14', 'spectre-x360-14'),
  ('hp', 'spectre', 'Spectre x360 16', 'spectre-x360-16'),
  ('hp', 'omnibook', 'OmniBook X 14', 'omnibook-x-14'),
  ('hp', 'omnibook', 'OmniBook Ultra 14', 'omnibook-ultra-14'),
  ('hp', 'omnibook', 'OmniBook 5 16', 'omnibook-5-16'),
  ('hp', 'omnibook', 'OmniBook 7 16', 'omnibook-7-16'),
  ('hp', 'elitebook', 'EliteBook 640', 'elitebook-640'),
  ('hp', 'elitebook', 'EliteBook 840', 'elitebook-840'),
  ('hp', 'elitebook', 'EliteBook 1040', 'elitebook-1040'),
  ('hp', 'elitebook', 'EliteBook Ultra', 'elitebook-ultra'),
  ('hp', 'probook', 'ProBook 440', 'probook-440'),
  ('hp', 'probook', 'ProBook 450', 'probook-450'),
  ('hp', 'probook', 'ProBook 460', 'probook-460'),
  ('hp', 'zbook', 'ZBook Firefly', 'zbook-firefly'),
  ('hp', 'zbook', 'ZBook Studio', 'zbook-studio'),
  ('hp', 'zbook', 'ZBook Fury', 'zbook-fury'),
  ('hp', 'omen', 'OMEN 16', 'omen-16'),
  ('hp', 'omen', 'OMEN 17', 'omen-17'),
  ('hp', 'victus', 'Victus 15', 'victus-15'),
  ('hp', 'victus', 'Victus 16', 'victus-16'),
  ('hp', 'chromebook', 'HP Chromebook 14', 'hp-chromebook-14'),
  ('hp', 'chromebook', 'HP Chromebook x360 14', 'hp-chromebook-x360-14'),
  ('huawei', 'matebook-d', 'MateBook D 14', 'matebook-d-14'),
  ('huawei', 'matebook-d', 'MateBook D 15', 'matebook-d-15'),
  ('huawei', 'matebook-d', 'MateBook D 16', 'matebook-d-16'),
  ('huawei', 'matebook', 'MateBook 14', 'matebook-14'),
  ('huawei', 'matebook-x', 'MateBook X Pro', 'matebook-x-pro'),
  ('huawei', 'matebook-e', 'MateBook E', 'matebook-e'),
  ('infinix', 'inbook', 'INBook X1', 'inbook-x1'),
  ('infinix', 'inbook', 'INBook X2', 'inbook-x2'),
  ('infinix', 'inbook', 'INBook X3', 'inbook-x3'),
  ('infinix', 'zerobook', 'ZeroBook 13', 'zerobook-13'),
  ('infinix', 'gt-book', 'GT Book', 'gt-book'),
  ('lenovo', 'ideapad', 'IdeaPad Slim 3', 'ideapad-slim-3'),
  ('lenovo', 'ideapad', 'IdeaPad Slim 5', 'ideapad-slim-5'),
  ('lenovo', 'ideapad', 'IdeaPad Pro 5', 'ideapad-pro-5'),
  ('lenovo', 'yoga', 'Yoga Slim 7', 'yoga-slim-7'),
  ('lenovo', 'yoga', 'Yoga 7 2-in-1', 'yoga-7-2-in-1'),
  ('lenovo', 'yoga', 'Yoga Pro 7', 'yoga-pro-7'),
  ('lenovo', 'yoga', 'Yoga Pro 9i', 'yoga-pro-9i'),
  ('lenovo', 'thinkpad', 'ThinkPad E14', 'thinkpad-e14'),
  ('lenovo', 'thinkpad', 'ThinkPad E16', 'thinkpad-e16'),
  ('lenovo', 'thinkpad', 'ThinkPad T14', 'thinkpad-t14'),
  ('lenovo', 'thinkpad', 'ThinkPad T16', 'thinkpad-t16'),
  ('lenovo', 'thinkpad', 'ThinkPad X1 Carbon', 'thinkpad-x1-carbon'),
  ('lenovo', 'thinkpad', 'ThinkPad X1 Yoga', 'thinkpad-x1-yoga'),
  ('lenovo', 'thinkpad', 'ThinkPad P14s', 'thinkpad-p14s'),
  ('lenovo', 'thinkpad', 'ThinkPad P16', 'thinkpad-p16'),
  ('lenovo', 'thinkbook', 'ThinkBook 14', 'thinkbook-14'),
  ('lenovo', 'thinkbook', 'ThinkBook 16', 'thinkbook-16'),
  ('lenovo', 'thinkbook', 'ThinkBook 14 2-in-1', 'thinkbook-14-2-in-1'),
  ('lenovo', 'legion', 'Legion 5', 'legion-5'),
  ('lenovo', 'legion', 'Legion 5 Pro', 'legion-5-pro'),
  ('lenovo', 'legion', 'Legion 7i', 'legion-7i'),
  ('lenovo', 'legion', 'Legion 9i', 'legion-9i'),
  ('lenovo', 'loq', 'LOQ 15', 'loq-15'),
  ('lenovo', 'loq', 'LOQ 16', 'loq-16'),
  ('lenovo', 'chromebook', 'IdeaPad Chromebook', 'ideapad-chromebook'),
  ('lg', 'gram', 'Gram 14', 'gram-14'),
  ('lg', 'gram', 'Gram 15', 'gram-15'),
  ('lg', 'gram', 'Gram 16', 'gram-16'),
  ('lg', 'gram', 'Gram 17', 'gram-17'),
  ('lg', 'gram-pro', 'Gram Pro 16', 'gram-pro-16'),
  ('lg', 'gram-pro', 'Gram Pro 17', 'gram-pro-17'),
  ('lg', 'gram-2-in-1', 'Gram 14 2-in-1', 'gram-14-2-in-1'),
  ('lg', 'gram-2-in-1', 'Gram 16 2-in-1', 'gram-16-2-in-1'),
  ('microsoft', 'surface-laptop', 'Surface Laptop 13.8-inch', 'surface-laptop-13-8-inch'),
  ('microsoft', 'surface-laptop', 'Surface Laptop 15-inch', 'surface-laptop-15-inch'),
  ('microsoft', 'surface-pro', 'Surface Pro', 'surface-pro'),
  ('microsoft', 'surface-laptop-studio', 'Surface Laptop Studio', 'surface-laptop-studio'),
  ('microsoft', 'surface-laptop-studio', 'Surface Laptop Studio 2', 'surface-laptop-studio-2'),
  ('microsoft', 'surface-laptop-go', 'Surface Laptop Go', 'surface-laptop-go'),
  ('msi', 'modern', 'Modern 14', 'modern-14'),
  ('msi', 'modern', 'Modern 15', 'modern-15'),
  ('msi', 'prestige', 'Prestige 13 AI', 'prestige-13-ai'),
  ('msi', 'prestige', 'Prestige 14 AI', 'prestige-14-ai'),
  ('msi', 'prestige', 'Prestige 16 AI', 'prestige-16-ai'),
  ('msi', 'summit', 'Summit E13', 'summit-e13'),
  ('msi', 'summit', 'Summit E16', 'summit-e16'),
  ('msi', 'creator', 'Creator M16', 'creator-m16'),
  ('msi', 'creator', 'Creator Z16', 'creator-z16'),
  ('msi', 'katana', 'Katana 15', 'katana-15'),
  ('msi', 'katana', 'Katana 17', 'katana-17'),
  ('msi', 'cyborg', 'Cyborg 15', 'cyborg-15'),
  ('msi', 'cyborg', 'Cyborg A15', 'cyborg-a15'),
  ('msi', 'thin', 'Thin 15', 'thin-15'),
  ('msi', 'stealth', 'Stealth 14', 'stealth-14'),
  ('msi', 'stealth', 'Stealth 16', 'stealth-16'),
  ('msi', 'stealth', 'Stealth 18', 'stealth-18'),
  ('msi', 'raider', 'Raider GE68', 'raider-ge68'),
  ('msi', 'raider', 'Raider GE78', 'raider-ge78'),
  ('msi', 'raider', 'Raider 18', 'raider-18'),
  ('msi', 'vector', 'Vector 16', 'vector-16'),
  ('msi', 'vector', 'Vector 17', 'vector-17'),
  ('msi', 'titan', 'Titan 18', 'titan-18'),
  ('razer', 'blade', 'Blade 14', 'blade-14'),
  ('razer', 'blade', 'Blade 15', 'blade-15'),
  ('razer', 'blade', 'Blade 16', 'blade-16'),
  ('razer', 'blade', 'Blade 18', 'blade-18'),
  ('realme', 'book', 'Realme Book', 'realme-book'),
  ('realme', 'book', 'Realme Book Slim', 'realme-book-slim'),
  ('realme', 'book', 'Realme Book Prime', 'realme-book-prime'),
  ('samsung', 'galaxy-book', 'Galaxy Book', 'galaxy-book'),
  ('samsung', 'galaxy-book', 'Galaxy Book 360', 'galaxy-book-360'),
  ('samsung', 'galaxy-book', 'Galaxy Book Pro', 'galaxy-book-pro'),
  ('samsung', 'galaxy-book', 'Galaxy Book Pro 360', 'galaxy-book-pro-360'),
  ('samsung', 'galaxy-book', 'Galaxy Book Ultra', 'galaxy-book-ultra'),
  ('vaio', 'sx', 'VAIO SX12', 'vaio-sx12'),
  ('vaio', 'sx', 'VAIO SX14', 'vaio-sx14'),
  ('vaio', 'fe', 'VAIO FE14', 'vaio-fe14'),
  ('vaio', 'fe', 'VAIO FE15', 'vaio-fe15'),
  ('vaio', 'fh', 'VAIO FH14', 'vaio-fh14'),
  ('xiaomi', 'mi-notebook', 'Mi Notebook 14', 'mi-notebook-14'),
  ('xiaomi', 'mi-notebook', 'Mi Notebook Ultra', 'mi-notebook-ultra'),
  ('xiaomi', 'redmibook', 'RedmiBook 15', 'redmibook-15'),
  ('xiaomi', 'redmibook', 'RedmiBook Pro', 'redmibook-pro'),
  ('xiaomi', 'xiaomi-book', 'Xiaomi Book S', 'xiaomi-book-s');

with resolved_models as (
  select series.id as series_id, seed.model_name, seed.model_slug
  from laptop_model_seed seed
  join public.brands brand
    on brand.service_type = 'laptop'
   and brand.slug = seed.brand_slug
  join public.series series
    on series.brand_id = brand.id
   and series.slug = seed.series_slug
)
insert into public.models (series_id, name, slug)
select series_id, model_name, model_slug
from resolved_models
on conflict (series_id, slug) do update
set name = excluded.name;

notify pgrst, 'reload schema';
